import type { Metadata } from "next";
import localFont from "next/font/local";
import global from "./globals.module.scss";

const workSans = localFont({
  src: "./fonts/work-sans/WorkSans-VariableFont_wght.woff",
  variable: "--font-work-sans",
  weight: "100 900",
});
const avenirSansBook = localFont({
  src: "./fonts/avenir-sans/AvenirLTStd-Book.woff",
  variable: "--font-avenir-sans-book",
  weight: "400",
});
const avenirSansBlack = localFont({
  src: "./fonts/avenir-sans/AvenirLTStd-Black.woff",
  variable: "--font-avenir-sans-black",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${workSans.variable} ${avenirSansBook.variable} ${avenirSansBlack.variable} ${global.html}`}
      >
        {children}
      </body>
    </html>
  );
}

