import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import variables from "./sass/variables.module.scss";

const workSans = localFont({
  src: "./fonts/work-sans/WorkSans-VariableFont_wght.woff",
  variable: "--font-work-sans",
  weight: "100 900",
});
const avenirNextRegular = localFont({
  src: "./fonts/avenir-next/AvenirNextLTPro-Regular.woff",
  variable: "--font-avenir-next-regular",
  weight: "400",
});
const avenirNextBold = localFont({
  src: "./fonts/avenir-next/AvenirNextLTPro-Bold.woff",
  variable: "--font-avenir-next-bold",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Lendsqr Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${workSans.variable} ${avenirNextRegular.variable} ${avenirNextBold.variable} ${variables.body} `}
      >
        {children}
      </body>
    </html>
  );
}

